apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poc-k8s-csharp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-k8s-csharp
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
